web/router.ex
defmodule Bazhovka.Router do
  use Bazhovka.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Bazhovka.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Bazhovka do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/payment_receipts", PaymentReceiptController, only: [:show]

    resources "/addresses", AddressController, only: [:index, :edit, :update] do
      resources "/calculations", AddressCalculationController, only: [:index]
      resources "/payments", AddressPaymentController, except: [:show]
    end

    resources "/indications", IndicationController, only: [:index, :new, :create, :delete, :update]
    get "/indications/history", IndicationsHistoryController, :index
    get "/indications/batch", IndicationController, :batch
    post "/indications/batch", IndicationController, :save_batch

    resources "/calculations", CalculationController, except: [:edit, :update]
    resources "/payments", PaymentController, only: [:index, :new, :create]
    resources "/users", UserController, except: [:show]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :token
    get "/password/edit", PasswordController, :edit
    put "/password", PasswordController, :update

    resources "/posts", PostController, except: [:index]
    resources "/my", PersonalController, only: [:index]

    resources "/documents", DocumentController

    resources "/folders", FolderController, except: [:show] do
      get "/", DocumentController, :index
    end

    resources "/polls", PollController, except: [:show] do
      post "/vote", VoteController, :create
    end
    post "/polls/:id/complete", PollController, :complete
    post "/polls/:id/resume", PollController, :resume
  end

  # Other scopes may use custom stacks.
  # scope "/api", Bazhovka do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Bazhovka.LayoutView do
  use Bazhovka.Web, :view
end

web/templates/layout/app.html.eex
<% user = current_user(@conn) %>

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Бажовка</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
     (function (d, w, c) {
         (w[c] = w[c] || []).push(function() {
             try {
                 w.yaCounter45655932 = new Ya.Metrika({
                     id:45655932,
                     clickmap:true,
                     trackLinks:true,
                     accurateTrackBounce:true
                 });
             } catch(e) { }
         });

         var n = d.getElementsByTagName("script")[0],
             s = d.createElement("script"),
             f = function () { n.parentNode.insertBefore(s, n); };
         s.type = "text/javascript";
         s.async = true;
         s.src = "https://mc.yandex.ru/metrika/watch.js";

         if (w.opera == "[object Opera]") {
             d.addEventListener("DOMContentLoaded", f, false);
         } else { f(); }
     })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/45655932" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">СОПК&nbsp;&laquo;Бажовка-1&raquo;</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
              <li><%= link "Главная", to: page_path(@conn, :index) %></li>
              <%= if user do %>
                  <li><%= link "Личный кабинет", to: personal_path(@conn, :index) %></li>
                  <li><%= link "Документы", to: folder_path(@conn, :index) %></li>
                  <%= if user.role == "admin" do %>
                      <li><%= link "Опросы", to: poll_path(@conn, :index) %></li>
                      <li><%= link "Адреса", to: address_path(@conn, :index) %></li>
                      <li><%= link "Показания", to: indication_path(@conn, :index) %></li>
                      <li><%= link "Расчёты э/э", to: calculation_path(@conn, :index) %></li>
                      <li><%= link "Платежи", to: payment_path(@conn, :index) %></li>
                      <li><%= link "Пользователи", to: user_path(@conn, :index) %></li>
                  <% end %>
              <% end %>

          </ul>
          <ul class="nav navbar-nav navbar-right">
              <%= if user do %>
                  <li></li>

                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= user.email %>
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                          <li><%= link "Сменить пароль", to: password_path(@conn, :edit) %></li>
                      </ul>
                  </li>

                  <li><%= link "Выйти", to: session_path(@conn, :delete) %></li>
              <% else %>
                  <li><%= link "Войти", to: session_path(@conn, :new) %></li>
              <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


    <div class="container-fluid" role="main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="row">
          <div class="col-md-12">
              <%= render @view_module, @view_template, assigns %>
          </div>
      </div>

    </div> <!-- /container -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>