web/router.ex
defmodule Bazhovka.Router do
  use Bazhovka.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Bazhovka.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Bazhovka do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/payment_receipts", PaymentReceiptController, only: [:show]

    resources "/addresses", AddressController, only: [:index, :edit, :update] do
      resources "/calculations", AddressCalculationController, only: [:index]
      resources "/payments", AddressPaymentController, except: [:show]
    end

    resources "/indications", IndicationController, only: [:index, :new, :create, :delete, :update]
    get "/indications/history", IndicationsHistoryController, :index
    get "/indications/batch", IndicationController, :batch
    post "/indications/batch", IndicationController, :save_batch

    resources "/calculations", CalculationController, except: [:edit, :update]
    resources "/payments", PaymentController, only: [:index, :new, :create]
    resources "/users", UserController, except: [:show]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/password/reset", PasswordController, :reset
    post "/password/reset", PasswordController, :token
    get "/password/edit", PasswordController, :edit
    put "/password", PasswordController, :update

    resources "/posts", PostController, except: [:index]
    resources "/my", PersonalController, only: [:index]

    resources "/documents", DocumentController

    resources "/folders", FolderController, except: [:show] do
      get "/", DocumentController, :index
    end

    resources "/polls", PollController, except: [:show] do
      post "/vote", VoteController, :create
    end
    post "/polls/:id/complete", PollController, :complete
    post "/polls/:id/resume", PollController, :resume
  end

  # Other scopes may use custom stacks.
  # scope "/api", Bazhovka do
  #   pipe_through :api
  # end
end

web/models/poll.ex
defmodule Bazhovka.Poll do
  use Bazhovka.Web, :model

  @key_length 12
  @default_questions "согласен\nвоздержался\nне согласен"

  schema "polls" do
    field :title, :string
    field :questions, :map
    field :questions_string, :string, virtual: true
    field :active, :boolean, default: false
    has_many :votes, Bazhovka.Vote

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :questions_string, :active])
    |> normalize_questions
    |> activate_new
    |> validate_required([:title, :questions])
  end

  defp normalize_questions(%Ecto.Changeset{changes: %{questions_string: questions_string}} = changeset)
  when is_bitstring(questions_string) do
    questions_as_map =
      questions_string
      |> String.split("\n")
      |> Enum.filter(fn(s) -> !is_nil(s) && s != "" end)
      |> Enum.map(&String.trim_trailing/1)
      |> Enum.reduce(%{}, fn(q, acc) -> Map.put(acc, random_key(Enum.count(acc)), q) end)

    put_change(changeset, :questions, questions_as_map)
  end

  defp normalize_questions(%Ecto.Changeset{data: %{questions: questions}} = changeset)
  when is_map(questions) do
    put_change(changeset, :questions_string, Enum.join(Map.values(questions), "\n"))
  end

  defp normalize_questions(%Ecto.Changeset{} = changeset) do
    put_change(changeset, :questions_string, @default_questions)
  end

  defp activate_new(%Ecto.Changeset{data: %{id: nil}} = changeset) do
    put_change(changeset, :active, true)
  end

  defp activate_new(%Ecto.Changeset{} = changeset) do
    changeset
  end

  defp random_key(position) do
    rand_part = :crypto.strong_rand_bytes(@key_length)
    |> Base.url_encode64

    "#{position}__#{rand_part}"
  end
end

web/controllers/poll_controller.ex
defmodule Bazhovka.PollController do
  use Bazhovka.Web, :controller
  import Ecto.Query, only: [from: 2]

  alias Bazhovka.Poll
  alias Bazhovka.PollService

  def index(conn, _params) do
    polls = PollService.load_polls()
    render(conn, "index.html", polls: polls)
  end

  def new(conn, _params) do
    changeset = Poll.changeset(%Poll{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"poll" => poll_params}) do
    changeset = Poll.changeset(%Poll{}, poll_params)

    case Repo.insert(changeset) do
      {:ok, _poll} ->
        conn
        |> put_flash(:info, "Опрос создан.")
        |> redirect(to: poll_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    poll = Repo.get!(Poll, id)
    changeset = Poll.changeset(poll)
    render(conn, "edit.html", poll: poll, changeset: changeset)
  end

  def update(conn, %{"id" => id, "poll" => poll_params}) do
    poll = Repo.get!(Poll, id)
    changeset = Poll.changeset(poll, poll_params)

    case Repo.update(changeset) do
      {:ok, poll} ->
        conn
        |> put_flash(:info, "Опрос обновлён.")
        |> redirect(to: poll_path(conn, :index))
      {:error, changeset} ->
        render(conn, "edit.html", poll: poll, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    poll = Repo.get!(Poll, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(poll)

    conn
    |> put_flash(:info, "Опрос удалён.")
    |> redirect(to: poll_path(conn, :index))
  end

  def complete(conn, %{"id" => id}) do
    Repo.get!(Poll, id)
    |> Poll.changeset(%{"active" => false})
    |> Repo.update!

    conn
    |> put_flash(:info, "Опрос завершён.")
    |> redirect(to: poll_path(conn, :index))
  end

  def resume(conn, %{"id" => id}) do
    Repo.get!(Poll, id)
    |> Poll.changeset(%{"active" => true})
    |> Repo.update!

    conn
    |> put_flash(:info, "Опрос возобновлён.")
    |> redirect(to: poll_path(conn, :index))
  end
end

web/views/poll_view.ex
defmodule Bazhovka.PollView do
  use Bazhovka.Web, :view

  def paste_code(poll) do
    "$(poll:#{poll.id})"
  end
end

web/templates/poll/edit.html.eex
<div class="page-header">
    <h2>Редактирование опроса</h2>
</div>

<div class="bs-callout bs-callout-danger">
    <h4>Внимание.</h4>
    <p>Редактировать запрос по которому уже есть ответы - плохая идея. Связь с существующими ответами будет потеряна.</p>
</div>

<%= render "form.html", changeset: @changeset,
                        action: poll_path(@conn, :update, @poll) %>

<%= link "Назад", to: poll_path(@conn, :index) %>

web/templates/poll/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, "Заголовок", class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :questions_string, "Варианты ответов", class: "control-label" %>
    <%= textarea f, :questions_string, class: "form-control", placeholder: "Одна строка - один вариант", rows: 4 %>
    <%= error_tag f, :questions_string %>
  </div>

  <div class="form-group">
    <%= submit "Сохранить", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/poll/index.html.eex
<div class="page-header">
    <h2>Опросы</h2>
    <%= link "Создать новый опрос", to: poll_path(@conn, :new), class: "btn btn-primary btn-sm" %>
</div>

<div class="col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
  <%= for poll <- @polls do %>
    <%= render "poll.html", poll: poll, admin_mode: current_user(@conn).role == "admin", conn: @conn %>
  <% end %>

</div>

web/templates/poll/new.html.eex
<div class="page-header">
  <h2>Создать опрос</h2>
</div>

<%= render "form.html", changeset: @changeset,
                        action: poll_path(@conn, :create) %>

<%= link "Назад", to: poll_path(@conn, :index) %>

web/templates/poll/poll.html.eex
<% vote_addr_index = Enum.reduce(@poll.votes, %{}, fn(v, acc) -> Map.put(acc, v.address_id, v.answer) end) %>
<% vote_poll_index = Enum.reduce(@poll.votes, %{}, fn(v, acc) -> Map.update(acc, v.answer, 1, &(&1 + 1)) end) %>
<% vote_count = Enum.count(@poll.votes) %>
<% percent = fn(answer) -> if vote_count > 0, do: Decimal.mult(Decimal.new(100), Decimal.div(Decimal.new(vote_poll_index[answer] || 0), Decimal.new(vote_count))), else: 0 end %>

<div class="panel panel-default">
    <div class="panel-heading">
        <%= @poll.title %>
        <%= if @admin_mode do %>
        <div class="pull-right">
            <%= link "Редактировать", to: poll_path(@conn, :edit, @poll), class: "btn btn-primary btn-xs" %>
            <%= if @poll.active do %>
                <%= link "Завершить", to: poll_path(@conn, :complete, @poll), method: :post, class: "btn btn-warning btn-xs" %>
            <% else %>
                <%= link "Возобновить", to: poll_path(@conn, :resume, @poll), method: :post, class: "btn btn-warning btn-xs" %>
            <% end %>
            <%= link "Удалить", to: poll_path(@conn, :delete, @poll), method: :delete, data: [confirm: "Удалить этот опрос?"], class: "btn btn-danger btn-xs" %>
        </div>
        <% end %>
    </div>
    <div class="panel-body">
        <%= if @admin_mode || !@poll.active do %>
            <%= for {k, q} <- @poll.questions do %>
                <h5><%= q %></h5>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: <%= percent.(k) %>%;">
                        <%= vote_poll_index[k] || 0 %>&nbsp;из&nbsp;<%= vote_count %>
                    </div>
                </div>
            <% end %>
        <% else %>
            <div class="btn-group" role="group" aria-label="...">
                <%= for {k, q} <- @poll.questions do %>
                    <% current_address = Bazhovka.AddressService.user_address(current_user(@conn)) %>
                    <% if current_address && vote_addr_index[current_address.id] == k do %>
                    <% btn_class = "btn btn-primary" %>
                    <% else %>
                    <% btn_class = "btn btn-default" %>
                    <% end %>
                    <%= link q, to: poll_vote_path(@conn, :create, @poll, answer: k, return_to: @conn.request_path), method: :post, class: btn_class %>
                <% end %>
            </div>
        <% end %>
    </div>
    <div class="panel-footer">
        <%= if !@poll.active, do: "Опрос завершён." %>
        <p>Проголосовали: <%= length(@poll.votes) %> чел.</p>
        <%= if @admin_mode do %>
            <p>
                Код для вставки:
                <input type="text" value="<%= paste_code(@poll) %>"/>
            </p>
        <% end %>
    </div>
</div>

web/templates/poll/show.html.eex
<h2>Show poll</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @poll.title %>
  </li>

  <li>
    <strong>Questions:</strong>
    <%= @poll.questions %>
  </li>

  <li>
    <strong>Active:</strong>
    <%= @poll.active %>
  </li>

</ul>

<%= link "Edit", to: poll_path(@conn, :edit, @poll) %>
<%= link "Back", to: poll_path(@conn, :index) %>